global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: 'ingestion'
    metrics_path: '/ingestion/metrics'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/dev.crt
      insecure_skip_verify: false
    static_configs:
      - targets: ['caddy:443']
        labels:
          service: ingestion
          component: ingestionservice
          environment: local

  - job_name: 'persistence'
    metrics_path: '/persistence/metrics'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/dev.crt
      insecure_skip_verify: false
    static_configs:
      - targets: ['caddy:443']
        labels:
          service: persistence
          component: persistenceservice
          environment: local
